import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getPages } from "../../../sanity/sanity-utils";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div>
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`}>
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
